---
title: "Tidying data"
author: "Joe DeCesaro"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

### Read in the wb_indicators.csv file, make sure to specify "na = c("..", "")"

```{r}
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))

```

### Reshape so that year is a single column
```{r}
wb_indicators_long <- wb_indicators %>% 
  pivot_longer(cols = '2001 [YR2001]':'2020 [YR2020]', 
               names_to = "year", 
               values_to = "indicator_value")

```

### Clean up that year column
```{r}
wb_indicators_sep <- wb_indicators_long %>% 
  separate(col = year, into = c("year", "year_chr"), sep = " ") %>% 
  select(-year_chr, -"Country Code", - "Series Code")
```

### Make a new data frame using tribble
```{r}
df <- tribble(
  ~name, ~A, ~B, ~C, 
  "teddy", 4, 5, 6, 
  "khora", 9, 10, 11
)

# If A, B, and C are dog food types, convert this into tidy format

df_long <- df %>% 
  pivot_longer(cols = A:C, 
               names_to = "dog_food",
               values_to = "rankings")

df_wide <- df_long %>% 
  pivot_wider(names_from = dog_food, values_from = rankings)
```

### Now we will made the indicators into seperate columns using pivot_wider
```{r}
wb_data_tidy <- wb_indicators_sep %>% 
  drop_na('Series Name') %>% 
  pivot_wider(names_from = 'Series Name', values_from = indicator_value)
```
This is now tidy! But the names of the columns are horrendous so lets help ourselves
```{r}
names(wb_data_tidy) <- c("country", "year", "access_clean_fuels", "access_electricity", "co2_emissions", "fossil_fuel_cons", "water_stress")

# could also use `rename(new.name = old.name)` for a single column

wb_data_tidy <- wb_data_tidy %>% 
  rename(country_name = country)
```





